# syntax=docker/dockerfile:1
FROM ubuntu:22.04

COPY . /shaunak

RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip install -r /shaunak/requirements.txt

WORKDIR /shaunak
ENV FLASK_APP=api
EXPOSE 8000

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "8000"]
